version: "3.7"
services:
  stormwater_api:
    build: .
    env_file: .env
    ports:
      - '8000:80'
    command: uvicorn stormwater_api.api.main:app --host 0.0.0.0 --port 80 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
  
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASS} --appendonly yes
    networks:
      &network_mode
      - bridgenet
    volumes:
      - "./redis/data:/data"
  
  celery_worker:
    container_name: celery_worker
    build: .
    restart: "always"
    command: celery -A stormwater_api.celery worker --loglevel=info
    networks:
      &network_mode
      - bridgenet
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - stormwater_api
      - redis

networks:
  bridgenet:
    driver: bridge