version: "3.7"
services:
  stormwater-api:
    build: .
    env_file: .env
    ports:
      - '8000:80'
    command: uvicorn stormwater_api.api.main:app --host 0.0.0.0 --port 80 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
  
  redis-stormwater:
    container_name: redis-stormwater
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  celery-worker-stormwater:
    container_name: celery-worker-stormwater
    build: .
    restart: "always"
    command: celery -A stormwater_api.tasks worker --loglevel=info
    networks: *network_mode
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - stormwater-api
      - redis-stormwater
  
  flower:
    container_name: flower-stormwater
    build: .
    command: celery -A stormwater_api.tasks flower --port=5555
    networks: *network_mode
    ports:
      - '5556:5555'
    env_file:
      - .env
    depends_on:
      - stormwater-api
      - redis-stormwater
      - celery-worker-stormwater

networks:
  bridgenet:
    driver: bridge