version: "3.7"

services:
  stormwater-api:
    build: .
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: uvicorn stormwater_api.api.main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
    depends_on:
      - celery-worker
      - redis
  
  redis:
    container_name: stormwater-redis
    image: redis:6.2-alpine
    expose: 
      - ${REDIS_PORT}
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  celery-worker:
    container_name: stormwater-celery-worker
    build: .
    restart: "always"
    command: celery -A stormwater_api.tasks worker --loglevel=info
    networks: *network_mode
    env_file:
      - .env
    volumes:
      - ./:/app

networks:
  bridgenet:
    driver: bridge