version: "3.7"
services:
  stormwater_api:
    build: .
    env_file: .env
    ports:
      - '8000:80'
    command: uvicorn stormwater_api.api.main:app --host 0.0.0.0 --port 80 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
  
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      # - ${REDIS_PORT}:${REDIS_PORT}
      - '6379:6379'
    restart: "always"
    command: redis-server --appendonly yes
    networks:
      &network_mode
      - bridgenet
    volumes:
      - "./redis/data:/data"
  
  celery_worker:
    container_name: celery_worker
    build: .
    restart: "always"
    command: celery -A stormwater_api.celery worker --loglevel=info
    networks:
      &network_mode
      - bridgenet
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - stormwater_api
      - redis
  
  flower:
    container_name: flower
    build: .
    command: celery -A stormwater_api.celery flower --port=5555
    networks:
      &network_mode
      - bridgenet
    ports:
      - '5556:5555'
    env_file:
      - .env
    depends_on:
      - stormwater_api
      - redis
      - celery_worker

networks:
  bridgenet:
    driver: bridge